/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prclient;

import java.util.Date;
import java.util.Properties;
import java.io.*;
import java. util.*;
import javax.swing.*;
import java.awt.*;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.*;
import javax.mail.internet.*;

/**
 *
 * @author ebadebesin
 */
public class prHomepage extends javax.swing.JFrame {

    prDatabaseC con = new prDatabaseC();
    prLogin log = new prLogin();
    
    String emailto;
    String userTo;
    
    /**
     * Creates new form prHomepage
     */
    public prHomepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        contactusButton = new javax.swing.JButton();
        looseweightButton = new javax.swing.JButton();
        gainweightButton = new javax.swing.JButton();
        GmealplanButton2 = new javax.swing.JButton();
        LmealplanButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POWER RANGERS FITNESS, LLC.");
        setPreferredSize(new java.awt.Dimension(850, 750));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("POWER RANGERS WORKOUT");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Get a Personalized Workout Schedule and Meal Plan");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Select a goal");

        contactusButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        contactusButton.setText("CONTACT US");
        contactusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactusButtonActionPerformed(evt);
            }
        });

        looseweightButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        looseweightButton.setText("Workout Plan");
        looseweightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                looseweightButtonActionPerformed(evt);
            }
        });

        gainweightButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        gainweightButton.setText("Workout Plan");
        gainweightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gainweightButtonActionPerformed(evt);
            }
        });

        GmealplanButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        GmealplanButton2.setText("Meal Plan");
        GmealplanButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GmealplanButton2ActionPerformed(evt);
            }
        });

        LmealplanButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LmealplanButton.setText("Meal Plan");
        LmealplanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LmealplanButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("I WANT TO GAIN WEIGHT!");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("I WANT TO LOOSE WEIGHT!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 57, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LmealplanButton, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(looseweightButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(gainweightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GmealplanButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(contactusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(299, 299, 299))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(looseweightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gainweightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LmealplanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GmealplanButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(contactusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gainweightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gainweightButtonActionPerformed
        // TODO add your handling code here:
        
        String userN =JOptionPane.showInputDialog(null,"Confirm name");
        String email =JOptionPane.showInputDialog(null,"Confirm Email");    
        
        final String SSL_FACTORY = "javax.net.ssl.SSLSocketFactory";
// Get a Properties object
        Properties props = System.getProperties();
        props.setProperty("mail.smtp.host", "smtp.gmail.com");
        props.setProperty("mail.smtp.socketFactory.class", SSL_FACTORY);
        props.setProperty("mail.smtp.socketFactory.fallback", "false");
        props.setProperty("mail.smtp.port", "465");//port: 465
        props.setProperty("mail.smtp.socketFactory.port", "465");
        //props.put("mail.smtp.starttls.required", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.ssl.protocols", "TLSv1.2");
        props.put("mail.smtp.auth", "true");
        props.put("mail.debug", "true");
        props.put("mail.store.protocol", "pop3");
        props.put("mail.transport.protocol", "smtp");
        final String username = "ebadebesin@gmail.com";//
        final String password = "aliciakeys";// Change  axlzidcutlgtiilw
        try {
            Session session = Session.getDefaultInstance(props,
                    new Authenticator() {
                        protected PasswordAuthentication getPasswordAuthentication() {
                            return new PasswordAuthentication(username, password);
                        }
                    });
// -- Create a new message --
            Message msg = new MimeMessage(session);
// -- Set the FROM and TO fields --
            emailto = email;
            userTo = userN;
            System.out.println("User name: "+userTo);
            System.out.println("Email: "+emailto);
            msg.setFrom(new InternetAddress("ebadebesin@gmail.com"));
            msg.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse(emailto, false));
            msg.setSubject("PR Fitness- Gain weight workout plan");

            msg.setContent("<b> Dear  </b>" + userTo +","+ "<br><br><b>GAIN WEIGHT WORKOUT:</b><br><br>\n" +
"5 days-a-week 1hr (2 upper body/ 2 lower body/ 1 full body) add challenging weights <br><br>\n" +
" \n" +
"Monday- glutes and quads <br>\n" +
"Warm up – 10 min stretch <br>\n" +
"Stair master 5 mins speed 5-8<br>\n" +
"Squats 5x10<br>\n" +
"Bulgarian split squats 3x10<br>\n" +
"Goblet squat 3x10<br>\n" +
"Walking lunges 4x 10 steps <br>\n" +
"Leg press variations 3x10 of each (wide feet & close feet) <br>\n" +
"Step ups hold at top 3x10 each leg<br>\n" +
" <br>\n" +
"Tuesday- Back and Biceps + abs<br><br>\n" +
"Warm up- 10 min stretch <br>\n" +
"Rack pulls 3x10<br>\n" +
"Under grip rows 3x10 <br>\n" +
"Alternating bicep curls 3x10<br>\n" +
"Assisted shin ups 3x 10(or as many as you can do) <br>\n" +
"Push ups 3x10<br>\n" +
"Straight arm lat pulls 3x10<br><br>\n" +
" \n" +
"Abs: <br>\n" +
"3x10<br>\n" +
"Crunches<br>  \n" +
"Knee tucks<br>\n" +
"Heel taps <br>\n" +
"Slow sit ups <br>\n" +
" \n" +
" <br>\n" +
"Wednesday – hamstrings and glutes <br><br>\n" +
"Warm up- 10 min stretch <br>\n" +
"Stair master 5 mins speed 5-8<br>\n" +
"Romanian Dead Lifts 5x10 <br>\n" +
"Kettle bell swings 3x10 <br>\n" +
"Somo squats 3x10 <br>\n" +
"Good mornings 3x10 <br>\n" +
"Hip thrust 5x10<br>\n" +
" <br>\n" +
"Thursday- chest, shoulders, and triceps + abs<br><br>\n" +
"Bench press 3x10 <br>\n" +
"Military press 3x10<br>\n" +
"\n" +
"\n" +
"ITYs 3x10<br>\n" +
"Tricep push down 3x10<br>\n" +
"Underhand tricep push down 3x10<br>\n" +
"Upright row 3x10<br><br>\n" +
"Abs: <br>\n" +
"3x10<br>\n" +
"Crunches<br>  \n" +
"Knee tucks<br>\n" +
"Heel taps <br>\n" +
"Slow sit ups <br><br>\n" +
" \n" +
" \n" +
"\n" +
"Friday- full body <br><br>\n" +
"This day you pick 5-8 exercises from any day that you want to do or try something fun like yoga, <br> take a walk, dance, go for a run, etc. Just move your body and have fun you earned it! <br><br>\n" +
"Remember progress is not linear, KEEP GOING, <br><br>\n" +
"POWER RANGERS FITNESS, LLC.<br>", "text/html");
            msg.setSentDate(new Date());
            Transport.send(msg);
            System.out.println("Message sent.");
        } catch (MessagingException eX) {
            System.out.println("Error when mailing, cause: " + eX);
        }
        catch(Exception es){
            
        }
        
        //ServerMessageEA.setText(" File Printed! Please check your email for more information ");
    }//GEN-LAST:event_gainweightButtonActionPerformed

    private void contactusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactusButtonActionPerformed
        // TODO add your handling code here:
        new prContact().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_contactusButtonActionPerformed

    private void looseweightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_looseweightButtonActionPerformed
        // TODO add your handling code here:
         String userN =JOptionPane.showInputDialog(null,"Confirm name");
        String email =JOptionPane.showInputDialog(null,"Confirm Email");    
        
        final String SSL_FACTORY = "javax.net.ssl.SSLSocketFactory";
// Get a Properties object
        Properties props = System.getProperties();
        props.setProperty("mail.smtp.host", "smtp.gmail.com");
        props.setProperty("mail.smtp.socketFactory.class", SSL_FACTORY);
        props.setProperty("mail.smtp.socketFactory.fallback", "false");
        props.setProperty("mail.smtp.port", "465");//port: 465
        props.setProperty("mail.smtp.socketFactory.port", "465");
        //props.put("mail.smtp.starttls.required", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.ssl.protocols", "TLSv1.2");
        props.put("mail.smtp.auth", "true");
        props.put("mail.debug", "true");
        props.put("mail.store.protocol", "pop3");
        props.put("mail.transport.protocol", "smtp");
        final String username = "ebadebesin@gmail.com";//
        final String password = "aliciakeys";// Change  axlzidcutlgtiilw
        try {
            Session session = Session.getDefaultInstance(props,
                    new Authenticator() {
                        protected PasswordAuthentication getPasswordAuthentication() {
                            return new PasswordAuthentication(username, password);
                        }
                    });
// -- Create a new message --
            Message msg = new MimeMessage(session);
// -- Set the FROM and TO fields --
            emailto = email;
            userTo = userN;
            System.out.println("User name: "+userTo);
            System.out.println("Email: "+emailto);
            msg.setFrom(new InternetAddress("ebadebesin@gmail.com"));
            msg.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse(emailto, false));
            msg.setSubject("PR Fitness- Loose weight workout plan");

            msg.setContent("<b> Dear  </b>" + userTo +","+ "<br><br><b>LOOSE WEIGHT WORKOUT</b><br><br>\n" +
"5 Workouts per week alternate between the 3:<br><br>\n" +
"Workout 1: <br>\n" +
"9 movements 50 seconds each 20 seconds rest <br>\n" +
"1.Kick Sit<br>\n" +
"2. high knees <br>\n" +
"3. Jumping jacks <br>\n" +
"4. windmills <br>\n" +
"5. high Kick with touch<br>  \n" +
"6. explosive squat with touch <br>\n" +
"7. Table top toe touches <br>\n" +
"8. butt kicks<br>\n" +
"9. curtsy lunges<br><br>\n" +
" \n" +
"Workout 2: <br>\n" +
"Warm up<br>\n" +
"30 jumping jacks <br>\n" +
"30 body weight squats <br>\n" +
"30 side to side squats <br>\n" +
"30 butt kicks <br>\n" +
"60 seconds each 15 second rest<br>\n" +
"Squat side punches <br>\n" +
"Plank shoulder taps<br>\n" +
"Plank clamshells left <br>\n" +
"Plank clamshells right <br>\n" +
"Tabletop toe touches <br>\n" +
"Hip thrust walkouts <br>\n" +
"Side crab walk with calf raises <br>\n" +
"Plank leg raises<br>\n" +
"Side lunge into deep lunge left  <br>\n" +
"Side lunge into deep lunge right  <br>\n" +
"Superman swimmers <br>\n" +
"Sit up<br>\n" +
"Cool off stretch<br>\n" +
"<br><br>\n" +
"Workout 3:<br> \n" +
"Go for a walk jog run for 10 mins<br>\n" +
"1min run, 1 min jog, 30 second walk<br><br>\n" +
"Keep going you got this, <br><br>\n" +
"POWER RANGERS FITNESS, LLC.",
                    "text/html");
            msg.setSentDate(new Date());
            Transport.send(msg);
            System.out.println("Message sent.");
        } catch (MessagingException eX) {
            System.out.println("Error when mailing, cause: " + eX);
        }
        catch(Exception es){
            
        }
        
    }//GEN-LAST:event_looseweightButtonActionPerformed

    private void GmealplanButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GmealplanButton2ActionPerformed
        // TODO add your handling code here:
        
         String userN =JOptionPane.showInputDialog(null,"Confirm name");
        String email =JOptionPane.showInputDialog(null,"Confirm Email");    
        
        final String SSL_FACTORY = "javax.net.ssl.SSLSocketFactory";
// Get a Properties object
        Properties props = System.getProperties();
        props.setProperty("mail.smtp.host", "smtp.gmail.com");
        props.setProperty("mail.smtp.socketFactory.class", SSL_FACTORY);
        props.setProperty("mail.smtp.socketFactory.fallback", "false");
        props.setProperty("mail.smtp.port", "465");//port: 465
        props.setProperty("mail.smtp.socketFactory.port", "465");
        //props.put("mail.smtp.starttls.required", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.ssl.protocols", "TLSv1.2");
        props.put("mail.smtp.auth", "true");
        props.put("mail.debug", "true");
        props.put("mail.store.protocol", "pop3");
        props.put("mail.transport.protocol", "smtp");
        final String username = "ebadebesin@gmail.com";//
        final String password = "aliciakeys";// Change  axlzidcutlgtiilw
        try {
            Session session = Session.getDefaultInstance(props,
                    new Authenticator() {
                        protected PasswordAuthentication getPasswordAuthentication() {
                            return new PasswordAuthentication(username, password);
                        }
                    });
// -- Create a new message --
            Message msg = new MimeMessage(session);
// -- Set the FROM and TO fields --
            emailto = email;
            userTo = userN;
            System.out.println("User name: "+userTo);
            System.out.println("Email: "+emailto);
            msg.setFrom(new InternetAddress("ebadebesin@gmail.com"));
            msg.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse(emailto, false));
            msg.setSubject("PR Fitness- Gain weight meal plan");

            msg.setContent("<b> Dear  " + userTo +"</b>,"+ "<br><br> <b>GAIN WEIGHT MEAL PLAN</b><br>\n" +
"Make sure you eat three times a day <br>\n" +
"You want to incorporate lots of protein, carbs, fruits and vegetables. <br>\n" +
"Get rid of diet culture eat what you want but just try to create a good balance <br>\n" +
"Incorporate chicken, potatoes, oatmeal, peanut butter, quinoa, salmon, postas<br>\n" +
"Protein shakes: protein powder, 1 cup oatmeal, 1 cup ice, 1 cup almond milk, 1 cup fruit, 1 cup <br>\n" +
"peanut butter<br><br>\n" +
"Happy eating!<br><br>\n" +
"POWER RANGERS FITNESS, LLC.",  "text/html");
            msg.setSentDate(new Date());
            Transport.send(msg);
            System.out.println("Message sent.");
        } catch (MessagingException eX) {
            System.out.println("Error when mailing, cause: " + eX);
        }
        catch(Exception es){
            
        }
    }//GEN-LAST:event_GmealplanButton2ActionPerformed

    private void LmealplanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LmealplanButtonActionPerformed
        // TODO add your handling code here:
         String userN =JOptionPane.showInputDialog(null,"Confirm name");
        String email =JOptionPane.showInputDialog(null,"Confirm Email");    
        
        final String SSL_FACTORY = "javax.net.ssl.SSLSocketFactory";
// Get a Properties object
        Properties props = System.getProperties();
        props.setProperty("mail.smtp.host", "smtp.gmail.com");
        props.setProperty("mail.smtp.socketFactory.class", SSL_FACTORY);
        props.setProperty("mail.smtp.socketFactory.fallback", "false");
        props.setProperty("mail.smtp.port", "465");//port: 465
        props.setProperty("mail.smtp.socketFactory.port", "465");
        //props.put("mail.smtp.starttls.required", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.ssl.protocols", "TLSv1.2");
        props.put("mail.smtp.auth", "true");
        props.put("mail.debug", "true");
        props.put("mail.store.protocol", "pop3");
        props.put("mail.transport.protocol", "smtp");
        final String username = "ebadebesin@gmail.com";//
        final String password = "aliciakeys";// Change  axlzidcutlgtiilw
        try {
            Session session = Session.getDefaultInstance(props,
                    new Authenticator() {
                        protected PasswordAuthentication getPasswordAuthentication() {
                            return new PasswordAuthentication(username, password);
                        }
                    });
// -- Create a new message --
            Message msg = new MimeMessage(session);
// -- Set the FROM and TO fields --
            emailto = email;
            userTo = userN;
            System.out.println("User name: "+userTo);
            System.out.println("Email: "+emailto);
            msg.setFrom(new InternetAddress("ebadebesin@gmail.com"));
            msg.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse(emailto, false));
            msg.setSubject("PR Fitness- Loose weight meal plan");

            msg.setContent("<b> Dear  </b>" + userTo +","+ "<br><br> <b>LOOSE WEIGHT MEAL PLAN</b><br><br>\n" +
"Good news! No diet needed. Just be mindful of what you are eating. Everything starts in the kitchen<br>\n" +
"In order to loose weight you do have to be in a caloric deficit, but that does not mean you can only<br>\n" +
"Eat salads. Green vegetables are good to incorporate to help with bloating or even try a greens<br> supplement. Eating a boiled egg in the morning for breakfast can help feel you up until lunch<br>\n" +
"And they’re full of protein. Remember creating a healthy relationship with food is important!<br>\n" +
"Don’t deprive yourself of anything. If you want ice cream, eat it! But don’t go get cake after try to<br> incorporate an extra veggie after. Balance is key!<br><br>\n" +
"Happy eating!<br><br>\n" +
"POWER RANGERS FITNESS, LLC.", "text/html");
            msg.setSentDate(new Date());
            Transport.send(msg);
            System.out.println("Message sent.");
        } catch (MessagingException eX) {
            System.out.println("Error when mailing, cause: " + eX);
        }
        catch(Exception es){
            
        }
    }//GEN-LAST:event_LmealplanButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prHomepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GmealplanButton2;
    private javax.swing.JButton LmealplanButton;
    private javax.swing.JButton contactusButton;
    private javax.swing.JButton gainweightButton;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JButton looseweightButton;
    // End of variables declaration//GEN-END:variables
}
